import {
  RlmVisualizationStatus,
  type RlmStoryboard,
  type RlmVisualizationEvent,
  type RlmVisualizationState,
} from "./contracts.js";
import { bounded } from "./storyboard.js";

/**
 * Builds the single self-contained storyboard page. The model's sanitized SVG is the hero panel;
 * every other panel is derived deterministically from state, so the page stays complete and
 * readable even when the model contributed nothing this revision.
 */
export function buildVisualizationHtml(
  state: RlmVisualizationState,
  storyboard: RlmStoryboard,
): string {
  const title = bounded(storyboard.title, 120) || `RLM run ${state.runId}`;
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${escapeHtml(title)}</title>`,
    `<style>${STYLESHEET}</style>`,
    "</head>",
    "<body>",
    masthead(state, title),
    "<main>",
    briefPanel(state, storyboard),
    heroPanel(state, storyboard),
    narrativePanel(storyboard),
    hierarchyPanel(state),
    ledgerPanel(state),
    flowPanel(state),
    diagnosticsPanel(state),
    "</main>",
    `<footer class="foot"><p>Generated by the weavekit RLM storyboard recorder. Revision ${state.revision}, last updated ${escapeHtml(state.updatedAt)}.</p></footer>`,
    "</body>",
    "</html>",
  ].join("\n");
}

function masthead(state: RlmVisualizationState, title: string): string {
  return [
    '<header class="masthead">',
    '<p class="eyebrow">Recursive Submind · control room</p>',
    `<h1>${escapeHtml(title)}</h1>`,
    '<dl class="chips">',
    chip("run", state.runId),
    chip("renderer", state.renderer),
    chip("status", state.runStatus, `status-${state.runStatus}`),
    chip("calls", String(state.events.length)),
    chip("revision", String(state.revision)),
    chip("updated", state.updatedAt),
    "</dl>",
    "</header>",
  ].join("");
}

function briefPanel(state: RlmVisualizationState, storyboard: RlmStoryboard): string {
  return section(
    "brief",
    "Run brief",
    [
      `<p class="objective">${escapeHtml(bounded(state.objective, 1200) || "No objective recorded.")}</p>`,
      `<p class="summary">${escapeHtml(bounded(storyboard.summary, 1200) || "No storyboard summary yet.")}</p>`,
      state.runSummary
        ? `<p class="final"><span class="tag">final</span> ${escapeHtml(bounded(state.runSummary, 1200))}</p>`
        : "",
      `<p class="meta">Started ${escapeHtml(state.startedAt)} · ${state.events.filter((event) => event.status === RlmVisualizationStatus.Failed).length} failed of ${state.events.length} completed delegations.</p>`,
    ].join(""),
  );
}

function heroPanel(state: RlmVisualizationState, storyboard: RlmStoryboard): string {
  const label = `Storyboard diagram for RLM run ${state.runId}: ${bounded(storyboard.summary, 300)}`;
  return [
    '<section class="panel hero" aria-labelledby="hero-heading">',
    '<h2 id="hero-heading">Storyboard</h2>',
    `<figure class="stage" role="img" aria-label="${escapeHtml(label)}">`,
    storyboard.svg,
    `<figcaption>${escapeHtml(bounded(storyboard.title, 200))}</figcaption>`,
    "</figure>",
    "</section>",
  ].join("");
}

function narrativePanel(storyboard: RlmStoryboard): string {
  const beats = storyboard.narrative.slice(0, 60).filter((beat) => beat.trim().length > 0);
  if (beats.length === 0) return "";
  return section(
    "narrative",
    "Progress narrative",
    `<ol class="beats">${beats.map((beat) => `<li>${escapeHtml(bounded(beat, 400))}</li>`).join("")}</ol>`,
  );
}

/** Renders the parent-child recursion tree that the ledger's `parentCallId` chain determines. */
function hierarchyPanel(state: RlmVisualizationState): string {
  const children = new Map<string, RlmVisualizationEvent[]>();
  const known = new Set(state.events.map((event) => event.callId));
  for (const event of state.events) {
    const parent = event.parentCallId && known.has(event.parentCallId) ? event.parentCallId : "";
    children.set(parent, [...(children.get(parent) ?? []), event]);
  }
  const render = (parent: string, seen: ReadonlySet<string>): string => {
    const nodes = children.get(parent) ?? [];
    if (nodes.length === 0) return "";
    const items = nodes
      .filter((event) => !seen.has(event.callId))
      .map((event) => {
        const nested = new Set([...seen, event.callId]);
        return [
          `<li class="node ${event.status}">`,
          `<span class="node-head"><span class="seq">#${event.sequence}</span> <span class="kind">${escapeHtml(event.action)}</span> <span class="profile">${escapeHtml(event.profile)}</span>`,
          event.harness ? ` <span class="harness">${escapeHtml(event.harness)}</span>` : "",
          ` <span class="depth">depth ${event.depth}</span> <span class="verdict">${escapeHtml(event.status)}</span></span>`,
          `<span class="node-body">${escapeHtml(bounded(event.prompt, 240))}</span>`,
          render(event.callId, nested),
          "</li>",
        ].join("");
      })
      .join("");
    return items ? `<ul class="tree">${items}</ul>` : "";
  };
  const tree = render("", new Set());
  return section("hierarchy", "Recursion hierarchy", tree || "<p>No delegations recorded yet.</p>");
}

function ledgerPanel(state: RlmVisualizationState): string {
  if (state.events.length === 0) {
    return section("ledger", "Chronological ledger", "<p>No delegations recorded yet.</p>");
  }
  const rows = state.events
    .map((event) =>
      [
        `<tr class="${event.status}">`,
        `<th scope="row">#${event.sequence}</th>`,
        `<td>${escapeHtml(event.action)}</td>`,
        `<td>${event.depth}</td>`,
        `<td><code>${escapeHtml(event.callId)}</code><br><span class="muted">parent ${escapeHtml(event.parentCallId ?? "root session")}</span></td>`,
        `<td>${escapeHtml(event.profile)}${event.harness ? `<br><span class="muted">${escapeHtml(event.harness)}</span>` : ""}${event.model ? `<br><span class="muted">${escapeHtml(event.model)}</span>` : ""}</td>`,
        `<td>${escapeHtml(bounded(event.prompt, 320))}</td>`,
        `<td>${escapeHtml(bounded(event.summary ?? event.error ?? "", 320))}</td>`,
        `<td class="verdict">${escapeHtml(event.status)}</td>`,
        `<td>${formatDuration(event.durationMs)}<br><span class="muted">${escapeHtml(event.completedAt)}</span></td>`,
        "</tr>",
      ].join(""),
    )
    .join("");
  return section(
    "ledger",
    "Chronological ledger",
    [
      '<div class="scroll">',
      "<table><caption>Every completed delegation, in the order the recorder observed it.</caption>",
      "<thead><tr>",
      ...["Seq", "Action", "Depth", "Call", "Profile", "Task", "Result", "Status", "Timing"].map(
        (heading) => `<th scope="col">${heading}</th>`,
      ),
      "</tr></thead>",
      `<tbody>${rows}</tbody>`,
      "</table>",
      "</div>",
    ].join(""),
  );
}

/** Decisions plus the dependency edges that carried information between sibling calls. */
function flowPanel(state: RlmVisualizationState): string {
  const flows = state.events.filter(
    (event) =>
      event.dependencyCallIds.length > 0 ||
      event.decisions.length > 0 ||
      event.artifacts.length > 0,
  );
  if (flows.length === 0) return "";
  const items = flows
    .map((event) =>
      [
        `<li><h3>#${event.sequence} <code>${escapeHtml(event.callId)}</code></h3>`,
        event.dependencyCallIds.length
          ? `<p class="edges"><span class="tag">consumes</span> ${event.dependencyCallIds.map((id) => `<code>${escapeHtml(id)}</code>`).join(" ")}</p>`
          : "",
        event.decisions.length
          ? `<ul class="decisions">${event.decisions
              .slice(0, 12)
              .map((decision) => `<li>${escapeHtml(bounded(decision, 300))}</li>`)
              .join("")}</ul>`
          : "",
        event.artifacts.length
          ? `<p class="artifacts"><span class="tag">artifacts</span> ${event.artifacts
              .slice(0, 12)
              .map((artifact) => `<code>${escapeHtml(bounded(artifact, 160))}</code>`)
              .join(" ")}</p>`
          : "",
        event.worktreePath
          ? `<p class="artifacts"><span class="tag">worktree</span> <code>${escapeHtml(bounded(event.worktreePath, 200))}</code></p>`
          : "",
        "</li>",
      ].join(""),
    )
    .join("");
  return section("flow", "Decisions and information flow", `<ul class="flows">${items}</ul>`);
}

function diagnosticsPanel(state: RlmVisualizationState): string {
  if (state.diagnostics.length === 0) return "";
  const items = state.diagnostics
    .slice(-20)
    .map(
      (diagnostic) =>
        `<li><span class="tag">${escapeHtml(diagnostic.stage)}</span> <span class="muted">${escapeHtml(diagnostic.observedAt)}</span> ${escapeHtml(bounded(diagnostic.message, 400))}</li>`,
    )
    .join("");
  return section(
    "diagnostics",
    "Visualization diagnostics",
    `<ul class="diagnostics">${items}</ul>`,
  );
}

function section(id: string, heading: string, body: string): string {
  return [
    `<section class="panel" id="${id}" aria-labelledby="${id}-heading">`,
    `<h2 id="${id}-heading">${escapeHtml(heading)}</h2>`,
    body,
    "</section>",
  ].join("");
}

function chip(label: string, value: string, extra = ""): string {
  return `<div class="chip ${extra}"><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`;
}

function formatDuration(durationMs: number): string {
  if (durationMs < 1000) return `${Math.max(0, Math.round(durationMs))} ms`;
  const seconds = durationMs / 1000;
  return seconds < 90 ? `${seconds.toFixed(1)} s` : `${(seconds / 60).toFixed(1)} min`;
}

export function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

const STYLESHEET = `
:root{--ink:#e6edf3;--dim:#8b98a5;--bg:#080b0f;--panel:#0e141b;--line:#1f2a36;--accent:#f0b429;--live:#58a6ff;--ok:#3fb950;--bad:#f85149;--mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace}
@media (prefers-color-scheme:light){:root{--ink:#10161d;--dim:#54616e;--bg:#f3f1ec;--panel:#fffdf8;--line:#d8d2c6;--accent:#9a6b00;--live:#0b5fbf;--ok:#1a7f37;--bad:#b32218}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;padding:0 0 4rem}
main{display:grid;gap:1.25rem;padding:1.25rem;max-width:1560px;margin:0 auto}
a{color:var(--live)}
.masthead{border-bottom:2px solid var(--line);padding:1.5rem 1.25rem 1rem;max-width:1560px;margin:0 auto}
.eyebrow{margin:0;font:600 11px/1 var(--mono);letter-spacing:.22em;text-transform:uppercase;color:var(--accent)}
.masthead h1{margin:.5rem 0 .9rem;font-size:clamp(1.5rem,3.4vw,2.5rem);line-height:1.1;letter-spacing:-.015em}
.chips{display:flex;flex-wrap:wrap;gap:.5rem;margin:0}
.chip{border:1px solid var(--line);background:var(--panel);padding:.25rem .6rem;display:flex;gap:.5rem;align-items:baseline}
.chip dt{font:600 10px/1.6 var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--dim);margin:0}
.chip dd{margin:0;font:13px/1.4 var(--mono)}
.chip.status-running dd{color:var(--live)}
.chip.status-succeeded dd{color:var(--ok)}
.chip.status-failed dd{color:var(--bad)}
.panel{border:1px solid var(--line);background:var(--panel);padding:1rem 1.15rem 1.25rem}
.panel h2{margin:0 0 .75rem;font:600 12px/1 var(--mono);letter-spacing:.2em;text-transform:uppercase;color:var(--accent);border-bottom:1px solid var(--line);padding-bottom:.6rem}
.objective{font-size:1.05rem;margin:0 0 .6rem}
.summary{margin:0 0 .6rem;color:var(--ink)}
.final{margin:0 0 .6rem}
.meta,.muted{color:var(--dim);font:12px/1.5 var(--mono)}
.tag{font:600 10px/1.6 var(--mono);letter-spacing:.12em;text-transform:uppercase;border:1px solid var(--line);padding:0 .35rem;color:var(--accent)}
.stage{margin:0;overflow-x:auto;border:1px solid var(--line);background:var(--bg);padding:.5rem}
.stage svg{display:block;width:100%;height:auto;max-width:100%}
.stage figcaption{margin-top:.5rem;color:var(--dim);font:12px/1.5 var(--mono)}
.beats{margin:0;padding-left:1.4rem;display:grid;gap:.35rem}
.tree,.tree ul{list-style:none;margin:0;padding:0}
.tree ul{margin-left:1.1rem;padding-left:.9rem;border-left:1px dashed var(--line)}
.node{margin:.4rem 0;padding-left:.6rem;border-left:3px solid var(--line)}
.node.succeeded{border-left-color:var(--ok)}
.node.failed{border-left-color:var(--bad)}
.node-head{display:flex;flex-wrap:wrap;gap:.5rem;font:12px/1.6 var(--mono)}
.node-head .seq{color:var(--accent)}
.node-head .kind{font-weight:700}
.node-head .depth,.node-head .harness,.node-head .profile{color:var(--dim)}
.node-body{display:block;margin:.15rem 0 .2rem;color:var(--ink)}
.scroll{overflow-x:auto}
table{border-collapse:collapse;width:100%;min-width:1040px;font-size:13px}
caption{text-align:left;color:var(--dim);font:12px/1.5 var(--mono);padding-bottom:.5rem}
th,td{border-bottom:1px solid var(--line);padding:.45rem .5rem;text-align:left;vertical-align:top}
thead th{font:600 10px/1.6 var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--dim);white-space:nowrap}
tbody tr.failed{background:color-mix(in srgb,var(--bad) 12%,transparent)}
td.verdict,.node-head .verdict{font:600 11px/1.6 var(--mono);text-transform:uppercase}
tr.succeeded .verdict,.node.succeeded .verdict{color:var(--ok)}
tr.failed .verdict,.node.failed .verdict{color:var(--bad)}
code{font:12px/1.5 var(--mono);word-break:break-all}
.flows{list-style:none;margin:0;padding:0;display:grid;gap:.8rem}
.flows h3{margin:0 0 .3rem;font:600 12px/1.4 var(--mono)}
.decisions{margin:.25rem 0 0;padding-left:1.2rem;display:grid;gap:.2rem}
.edges,.artifacts{margin:.25rem 0;display:flex;flex-wrap:wrap;gap:.35rem;align-items:baseline}
.diagnostics{list-style:none;margin:0;padding:0;display:grid;gap:.4rem;color:var(--bad)}
.foot{max-width:1560px;margin:0 auto;padding:0 1.25rem;color:var(--dim);font:12px/1.5 var(--mono)}
:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
@media (max-width:720px){main{padding:.75rem}.panel{padding:.85rem}}
@media print{body{background:#fff;color:#000}.panel{break-inside:avoid}}
`.trim();
